steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - hallo-world
      - --region=europe-north1
      - --source=.
      - --trigger-http
      - --runtime=python310
      - --memory=128MB
      - --timeout=90
      - --min-instances=0
      - --max-instances=1
      - --security-level=secure-always
      - --ingress-settings=all
      - --no-allow-unauthenticated
      - --service-account=test-functions@emelleby.iam.gserviceaccount.com
